server:
  port: 8000
  servlet:
    context-path: /
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # ?? ??? ?? CORS ??
            allowed-origins:
               - "http://localhost:3000"
#              - "https://buysellgo.shop"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
            allow-credentials: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: BuySellGo Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
      routes:
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
            - Method=GET

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        - id: helpdesk-service-api-docs
          uri: lb://HELPDESK-SERVICE
          predicates:
            - Path=/helpdesk-service/v3/api-docs
            - Method=GET

        - id: helpdesk-service
          uri: lb://HELPDESK-SERVICE
          predicates:
            - Path=/helpdesk-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/helpdesk-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: helpdesk-service
          uri: lb://HELPDESK-SERVICE
          predicates:
            - Path=/helpdesk-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/helpdesk-service/(?<segment>.*), /$\{segment}


        - id: promotion-service-api-docs
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/promotion-service/v3/api-docs
            - Method=GET

        - id: promotion-service
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/promotion-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/promotion-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: promotion-service
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/promotion-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/promotion-service/(?<segment>.*), /$\{segment}

        - id: statistics-service-api-docs
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/statistics-service/v3/api-docs
            - Method=GET

        - id: statistics-service
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/statistics-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/statistics-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: statistics-service
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/statistics-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/statistics-service/(?<segment>.*), /$\{segment}

        - id: delivery-service-api-docs
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/v3/api-docs
            - Method=GET

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}


#        - id: openapi-proxy
#          uri: http://localhost:8000
#          predicates:
#          - Path=/demo-microservices/v3/api-docs/**
#          filters:
#          - RewritePath=/demo-microservices/v3/api-docs/(?<path>.*), /demo-microservices/$\{path}/v3/api-docs

#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#
#        - id: main-service
#          uri: lb://MAIN-SERVICE
#          predicates:
#            - Path=/main-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/main-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
#
#        - id: main-service
#          uri: lb://MAIN-SERVICE
#          predicates:
#            - Path=/main-service/actuator/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#        - id: mypage-service
#          uri: lb://MYPAGE-SERVICE
#          predicates:
#            - Path=/mypage-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/mypage-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
#
#        - id: mypage-service
#          uri: lb://MYPAGE-SERVICE
#          predicates:
#            - Path=/mypage-service/actuator/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#        - id: travelboard-service
#          uri: lb://TRAVELBOARD-SERVICE
#          predicates:
#            - Path=/travelboard-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/travelboard-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
#
#        - id: travelboard-service
#          uri: lb://TRAVELBOARD-SERVICE
#          predicates:
#            - Path=/travelboard-service/actuator/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
# log level setting
logging:
  level:
    logging:
      level:
        root: info
        org.hibernate.orm.jdbc.bind: info
        org.hibernate.SQL: info
        springframework.cloud.config: info
        com.buysellgo: info

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
#        primaryName: API Gateway Service
      - url: /user-service/v3/api-docs
        name: User Service
#        primaryName: User Service
      - url: /product-service/v3/api-docs
        name: Product Service
#        primaryName: Order Service
      - url: /order-service/v3/api-docs
        name: Order Service
#        primaryName: Order Service
      - url: /helpdesk-service/v3/api-docs
        name: HelpDesk Service
#        primaryName: HelpDesk Service
      - url: /promotion-service/v3/api-docs
        name: Promotion Service
#        primaryName: Promotion Service
      - url: /statistics-service/v3/api-docs
        name: Statistics Service
#        primaryName: Statistics Service
      - url: /delivery-service/v3/api-docs
        name: Delivery Service
#        primaryName: Delivery Service